### ISSUE TITLE
Orchestration Store empty

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-java-spring#16]
Hello there,

currently I want to create a demonstrator with this skeleton. The producer can successfully connect with the core systems but the consumer always get an empty response from the orchestrator. When I check the orchestrator store with the swagger api it is empty.

This is the error message I always get from the function proceedOrchestration:
> Caused by: eu.arrowhead.common.exception.InvalidParameterException: Consumer with name: TESTCONSUMER, address: 192.168.137.1 and port: 8123 is not exist in the database.
[source_code.zip](https://github.com/arrowhead-f/client-skeleton-java-spring/files/4071743/source_code.zip)

In the attachement you can find my source code.

Sincerely
BlackRose01

**Comment by borditamas** [comment]
Hello,
1) Did you set the authorization rules? As this is a sysop task you should do it manually if not yet done. Check this [hint](https://github.com/arrowhead-f/sos-examples-spring#requirements).
2) As far as I see in your source code you are triggering a diynamic orchestration (based on the orchestration flags). In this case you have nothing to deal with orchestration store.

**Comment by BlackRose01** [comment]
OK. I set the OVERRIDE_STORE flag to false and create the authorization rule now but the problem is still present.

So I created the Consumer in Swagger (ServiceRegistry: /serviceregsitry/mgmt/systems):
`{
  "address": "192.168.137.1",
  "authenticationInfo": null,
  "port": 8123,
  "systemName": "TESTCONSUMER"
}`

Response: id=16

This is the JSON for the Authorization Rule:
`{
  "consumerId": 16,
  "interfaceIds": [
    2
  ],
  "providerIds": [
    9
  ],
  "serviceDefinitionIds": [
    17, 18, 19, 20, 21, 22
  ]
}`

And in the attachment you can find the tables.
[table_content.txt](https://github.com/arrowhead-f/client-skeleton-java-spring/files/4072953/table_content.txt)

**Comment by MaGaMeGa** [comment]
Hi, 
If you set OVERRIDE_STORE to false, then the ORCHESTRATOR will try to use the store. Set it to true, if you do not want to use the store.

You did not included the authorization_intra_cloud_interface_connection table.
Please, make sure that it is not empty.
