### ISSUE TITLE
Strange dependancy?

### ISSUE THREAD

**Issue by jenseliasson** [arrowhead-f/client-java-spring#19]
client-library version 4.1.3.13 is referenced from the pom file. But only versions up to 4.1.3.7 are available on the repository.

**Comment by borditamas** [comment]
Hello,
after 4.1.3.7 we have changed the distribution to [GitHUB Packages](https://github.com/orgs/arrowhead-f/packages) (as the requirements section refers to it) because it is  a "more official way".
