### ISSUE TITLE
maven can't find arrowhead

### ISSUE THREAD

**Issue by armmkh** [arrowhead-f/client-java-spring#28]
Hello,
I tried installing this on two different machines and they give the exact same error:

[ERROR] Failed to execute goal on project arrowhead-client-skeleton-consumer: Could not resolve dependencies for project eu.arrowhead:arrowhead-client-skeleton-consumer:jar:4.1.3.3: Could not find artifact eu.arrowhead:client-library:jar:4.1.3.13 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

it looks like maven does not know how to find arrowhead.
Can you take a look please?

best regards,
Alireza

**Comment by tsvetlin** [comment]
Hello!

Have you configured Maven to use GitHub packages as it is written the README?

GitHub Packages [Configuring Maven for GitHub Packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages) |[ Example](https://github.com/arrowhead-f/application-library-java-spring/blob/master/docs/example_mvn_settings.xml)

**Comment by armmkh** [comment]
Thanks. it looked like that solved the issue.
But now I have another problem:
I have registered my provider skeleton, but when I try to reach it using the consumer, I get this:

Consumer with name: CONSUMER_SKELETON, address: 127.0.0.1 and port: 8011 is not exist in the database.

I also tried with my own public IP and other ports, same error.
Could you please help?

**Comment by borditamas** [comment]
The released consumer skeleton doesn't registrate itself into the ServiceRegistry since you have to manually set up the authotization rules anyway and for that you will need the id of the consumer.

This video could help you out to set up a working consumer-provider relationship:
https://www.youtube.com/watch?v=9BHemnv3mQA&t=783s
